#!/bin/bash
# Brokerage Setup Guide

echo "🏦 AutoTrader Brokerage Setup Guide"
echo "=================================="
echo ""

echo "📈 STOCK TRADING - ALPACA (RECOMMENDED)"
echo "----------------------------------------"
echo "✅ FREE trading (no commissions)"
echo "✅ No minimum deposit"
echo "✅ Easy API setup"
echo ""
echo "Steps:"
echo "1. Go to: https://alpaca.markets/"
echo "2. Sign up for free account"
echo "3. Verify your identity (standard KYC)"
echo "4. Go to Dashboard → API Keys → Generate New Key"
echo "5. Copy your API_KEY and SECRET_KEY"
echo "6. Update config/brokerage_config.json"
echo ""

echo "₿ CRYPTO TRADING - BINANCE (RECOMMENDED)"
echo "----------------------------------------"
echo "✅ Low fees (0.1% trading fees)"
echo "✅ No minimum deposit"
echo "✅ High liquidity"
echo ""
echo "Steps:"
echo "1. Go to: https://www.binance.com/"
echo "2. Sign up for free account"
echo "3. Verify your identity (for larger amounts)"
echo "4. Go to API Management → Create API"
echo "5. Copy your API_KEY and SECRET_KEY"
echo "6. Update config/brokerage_config.json"
echo ""

echo "💰 COSTS BREAKDOWN:"
echo "-------------------"
echo "• Alpaca: FREE (no commissions, no monthly fees)"
echo "• Binance: 0.1% per trade (very low)"
echo "• Bank transfers: Usually FREE"
echo "• Your system: FREE (runs on your Mac)"
echo ""

echo "🔧 NEXT STEPS:"
echo "--------------"
echo "1. Set up brokerage accounts (links above)"
echo "2. Get API keys from each brokerage"
echo "3. Update config/brokerage_config.json with your keys"
echo "4. Test with paper trading first"
echo "5. Start with small amount ($500)"
echo ""

echo "⚠️  SECURITY TIPS:"
echo "-----------------"
echo "• Never share your API keys"
echo "• Use paper trading first"
echo "• Start with small amounts"
echo "• Monitor your trades daily"
echo ""

echo "📞 SUPPORT:"
echo "----------"
echo "• Alpaca: https://alpaca.markets/support"
echo "• Binance: https://www.binance.com/en/support"
echo "• Your system: Check logs/ folder for issues"
echo ""

echo "🎯 RECOMMENDED STARTING AMOUNT: $500"
echo "   Expected return: 24% annually = $120 profit"
echo "   Risk: 9.3% max drawdown = $46 max loss"
echo ""
